[%General]
#界面风格，预留
style_mode=0

#程序运行名称，为了通过FindWindow函数查找
local_window_name=Bend_OCR_System
comm_window_name=prodove_comm

#共享内存
to_plc_share_mem_name=MEM_L2_PLC_COMM
from_plc_share_mem_name=MEM_PLC_L2_COMM

#工位数量
work_station_num=2

#界面刷新时间与采样时间
data_refresh_ms=200
data_refresh_s=2000
sample_period=200

#是否测试模式
test_mode=0

#是否保存录像
write_rot_video=0

[workstation1]
#序号
serialNumber=1
#工位位置：垛板台
location=stackerTable

#相机
front_ip_addr=192.168.1.101
front_expTime=5000
front_gain=23
front_frameRate=4
front_camera_res_width=4096
front_camera_res_height=2460

#数据库
DbType=SQLSERVER
DbName=camber_control
HostName=127.0.0.1
HostPort=1433
UserName=sa
UserPwd=ralautomation
TableName=BufferData
KeyName=utc,recogID,path,error

#mqtt
mqtt_use=1
mqtt_trigger_time=200
mqtt_hostname=127.0.0.1
mqtt_port=1883
mqtt_save_image_path=D:/data/hard_samples/
mqtt_image_cycle_num=50
mqtt_public_msg=ocr/stackerTable/msg

[workstation2]
#序号
serialNumber=2
#工位位置：热送
location=hotCharging

#相机
front_ip_addr=192.168.1.102
front_expTime=5000
front_gain=23
front_frameRate=4
front_camera_res_width=4096
front_camera_res_height=2460

#数据库
DbType=SQLSERVER
DbName=camber_control
HostName=127.0.0.1
HostPort=1433
UserName=sa
UserPwd=ralautomation
TableName=BufferData
KeyName=utc,recogID,path,error

#mqtt
mqtt_use=1
mqtt_trigger_time=200
mqtt_hostname=127.0.0.1
mqtt_port=1883
mqtt_save_image_path=D:/data/hard_samples/
mqtt_image_cycle_num=50
mqtt_public_msg=ocr/hotCharging/msg

[Db1Config]
DbType=SQLSERVER
DbName=camber_control
HostName=127.0.0.1
HostPort=1433
UserName=sa
UserPwd=ralautomation

#相机访问设定
[CameraFront]
front_ip_addr=172.166.111.233
#相机设定参数
front_expTime=17000
front_gain=0
front_frameRate=20
front_camera_res_width=4096
front_camera_res_height=2160

[CameraBack]
back_ip_addr=192.168.1.64
#相机设定参数
back_expTime=18000
back_gain=0
back_frameRate=20
back_camera_res_width=1280
back_camera_res_height=1024

#相机测量设定
[DetectGeneral]
calibrate_path=image_calibrate
test_path=image_test
save_path=E:/HeadData/image_data

[Img]
save_path=D:/data/buffer_imgs/

[MQTT]
mqtt_use=1
mqtt_trigger_time=200
mqtt_hostname=127.0.0.1
mqtt_port=1883
mqtt_save_image_path=D:/data/hard_samples/
mqtt_image_cycle_num=50

[JK]
ip=192.168.1.64
port=8000
user=admin
password=ral325..
